### ISSUE TITLE
natto.api.MeCabError: MECAB_NBEST request type is not set

### ISSUE THREAD

**Issue by himkt** [buruzaemon/natto-py#83]
I got the error when I use break statement in for-loop.

```python
for n in nm.parse("おめぇ誰より卓球好きじゃんよ!", as_nodes=True):
    print(n.feature)
    break
```

I'm sorry but I don't have any clue about this error...

**Comment by himkt** [comment]
maybe related to this issue

https://github.com/buruzaemon/natto-py/blob/master/natto/mecab.py#L165

https://github.com/buruzaemon/natto-py/blob/master/natto/mecab.py#L167

**Comment by buruzaemon** [comment]
Thanks, I will take a closer look at this during this weekend.

Brooke@iPhone

2016/01/22 16:49$B!"(Bhimkt <notifications@github.com> $B$N%a%C%;!<%8(B:

**Comment by buruzaemon** [comment]
Very interesting, this is immediately reproduce-able with @himkt's instructions...!

**Comment by himkt** [comment]
Oops! It's very strange... 

My developent environment is bellow:

OS      : OSX 10.11.2
Python: Anaconda3-2.4.0
natto   : 01.17

If I noticed anything, I would report here.

**Comment by buruzaemon** [comment]
I was also able to see this error on my Windows 7 laptop, and I am pretty sure I saw this at work on Linux environments as well. Thank you for raising this issue, @himkt.

**Comment by buruzaemon** [comment]
I think natto needs to catch and handle/ignore the [GeneratorExit exception](https://docs.python.org/3/library/exceptions.html) that comes when the [generator's close method](https://docs.python.org/2/whatsnew/2.5.html#pep-342) is invoked.

c.f. http://stackoverflow.com/questions/18637048/avoid-exception-ignored-in-python-enhanced-generator

**Comment by buruzaemon** [comment]
Looking at Mecab's src/tagger.cpp, line 784, you can see that the error "MECAB_NBEST request type is not set" comes when LatticeImpl::next() is invoked, meaning that this is happening **_after_** the Python generator's close method is called.

**Comment by buruzaemon** [comment]
Solution is to explicitly trap the GeneratorExit error. Fixed, will make this available in the next release, tomorrow.

**Comment by himkt** [comment]
I see. Thx :+1:

**Comment by kohchuanhock** [comment]
Is this also fixed for Ubuntu? I seems to be having this exception in 0.8.0

`Traceback (most recent call last):
  File "aiteacher.py", line 48, in <module>
    main(sys.argv)
  File "aiteacher.py", line 44, in main
    print(is_correct(question, user_sentence, correct_sentences, incorrect_sentences))
  File "aiteacher.py", line 10, in is_correct
    return v2.is_match(user_sentence, correct_sentences, incorrect_sentences)
  File "/home/ubuntu/aiteacher-ai/src/v2.py", line 85, in is_match
    if compare(input_sentence, correct_sentence):
  File "/home/ubuntu/aiteacher-ai/src/v2.py", line 31, in compare
    input_nodes = convert_to_list(nm.parse(input_sentence, as_nodes=True))
  File "/home/ubuntu/aiteacher-ai/src/v2.py", line 12, in convert_to_list
    for n in nodes:
  File "/usr/local/lib/python2.7/dist-packages/natto/mecab.py", line 413, in __parse_tonodes
    raise MeCabError(self.__bytes2str(self.__ffi.string(err)))
natto.api.MeCabError: MECAB_NBEST request type is not set`

**Comment by kohchuanhock** [comment]
The following code will cause the "natto.api.MeCabError: MECAB_NBEST request type is not set" error

# -*- coding: utf-8 -*-
from natto import MeCab

nm = MeCab('-F%m,%f[0],%f[1],%f[8]')
for n in nm.parse('私はアシャです', as_nodes=True):
    print(n.feature)

**Comment by himkt** [comment]
I have confirmed @kohchuanhock-san's error can be reproduced.
This error has occurred when `__%f[8]__` is used in the -F option.

To: @buruzaemon

**Comment by kohchuanhock** [comment]
@buruzaemon -san, 

Thank you very much for your quick response. I have created new issue.
https://github.com/buruzaemon/natto-py/issues/95

Thanks,

**Comment by buruzaemon** [comment]
Thank you, @himkt. I will have a deeper look into @kohchuanhock's reported
error, giving consideration to your steps for reproducing.
