### ISSUE TITLE
How to tokenize sentence with several user dict?

### ISSUE THREAD

**Issue by eromoe** [buruzaemon/natto-py#90]
I want use the default dict with some my additional dict.
google find out a cmd as below:
``` 
mecab -u dic1.dic,dic2.dic
```

But how to make it by natto?

**Comment by eromoe** [comment]
Oh, I figure it out
```
userdict = [xxx,xxx]
mc = MeCab("-u "+','.join(userdict)+" -F%m")
```

**Comment by buruzaemon** [comment]
Yes, you are correct. This is the same as the mecab command-line options.

Brooke@iPhone

2016/03/08 11:44$B!"(Beromoe <notifications@github.com> $B$N%a%C%;!<%8(B:
