### ISSUE TITLE
How to switch between two dictionaries?

### ISSUE THREAD

**Issue by evilplanet** [buruzaemon/natto-py#97]
I'm using Mecab to process both Japanese and Korean texts, I have two dictionary files. How do I specify a particular dictionary when instantiating Mecab in a function? Thank you!

**Comment by buruzaemon** [comment]
If you mean to keep use 2 dictionary files separately, then you could create 2 separate instances of `MeCab`. 

Hello, @evilplanet, and thanks for using natto-py...

You can specify a system dictionary with the mecab option [`--dicdir`](https://github.com/buruzaemon/natto-py/wiki/dicdir) or a custom user dictionary with [`--userdic`](https://github.com/buruzaemon/natto-py/wiki/userdic). Pass in these options when you instantiate `MeCab`.

**Comment by evilplanet** [comment]
I have modified `/usr/local/etc/mecabrc` as below:
```
dicdir =  /usr/local/lib/mecab/dic/ipadic
userdic = /usr/local/lib/mecab/dic/mecab-ko-dic/sys.dic
```

**Comment by evilplanet** [comment]
Below is my `/usr/local/etc/mecabrc` file:
```
; Configuration file of MeCab
;
; $Id: mecabrc.in,v 1.3 2006/05/29 15:36:08 taku-ku Exp $;
;
dicdir =  /usr/local/lib/mecab/dic/ipadic

; userdic = /usr/local/lib/mecab/dic/mecab-ko-dic

; output-format-type = wakati
; input-buffer-size = 8192

; node-format = %m\n
; bos-format = %S\n
; eos-format = EOS\n

```
When I tried to uncomment userdic, I can no longer instantiate MeCab.

**Comment by buruzaemon** [comment]
`natto-py` honors nearly the exact same options as when you use `mecab` from the command-line.

So the following two approaches are equivalent:

    # mecab from command-line
    mecab --dicdir=/usr/local/lib/mecab/dic/mecab-ko-dic

    # with natto-py
    nm = MeCab('--dicdir=/usr/local/lib/mecab/dic/mecab-ko-dic')

It is a good idea to try out your choice of options first at the `mecab` command-line before using them in instantiating `MeCab()` with `natto-py`.

Hope that helps!

**Comment by evilplanet** [comment]
It certainly helps! I wasn't sure how to set dict path and the other option together. Then I tried to chain them in a single string like this `MeCab('--dicdir=/usr/local/lib/mecab/dic/mecab-ko-dic -Owakati')` And it seems to be working. Thank you a lot!

**Comment by buruzaemon** [comment]
@evilplanet, I am glad to hear that you were able to correctly use both `-O` and `--dicdir` together. 

`natto-py` is meant to use the options in the same manner as they are passed to the `mecab` command-line, in order to be as familiar as possible, and so that is why you have to specify all of the options at instantiation time. 

Beside using a single, long options string, you can also use key-value pairs in `dict`.

For example, these are equivalent:

    # a single, long string
    MeCab('--dicdir=/usr/local/lib/mecab/dic/mecab-ko-dic -Owakati')

    # a dict with key-values
    MeCab({ 'dicdir': '/usr/local/lib/mecab/dic/mecab-ko-dic',
            'output_format_type': 'wakati' })

You can review the various `MeCab` options in the project Wiki's [Appendix B: Supported MeCab Options](https://github.com/buruzaemon/natto-py/wiki/Supported-MeCab-Options).

**Comment by evilplanet** [comment]
@buruzaemon  Great!! Thanks a lot. That's very informative!
